#!/usr/bin/env python3

from os import makedirs, path as fs
import sys
import yaml

__appname__ = "forestanza"


class FileLoader:
    CONFIGDIR = fs.dirname(fs.abspath(sys.argv[0]))
    CACHEDIR = fs.join(fs.expanduser('~/.cache'), __appname__)

    def expand_pj(path):
        if not isinstance(path, str):
            return path
        elif path.startswith(":/"):
            return fs.join(FileLoader.CONFIGDIR, path[2:])
        elif path.startswith("@/"):
            if not fs.exists(FileLoader.CACHEDIR):
                makedirs(FileLoader.CACHEDIR)
            return fs.join(FileLoader.CACHEDIR, path[2:])

    # ATTENTION: consider using OrderedDict, if cached .vimrc
    #   is supposed to be included under VCS
    def import_yaml(name):
        path = ':/../cfg/' + name + '.yml'
        with open(FileLoader.expand_pj(path)) as f:
            return yaml.safe_load(f)

    def export_cache(name, lines):
        path = '@/' + name + '.vim'
        with open(FileLoader.expand_pj(path), 'w') as f:
            f.writelines(lines)


class ParseError(Exception):
    """Base class for this program exceptions."""
    pass


def _F_selector(key, idx, main=False):
    def selector_instance(entry):
        ## WARNING can't be dict, as Flatten will expand all items!
        # if isinstance(entry, dict):
        #     return entry.get(key)
        if isinstance(entry, list):
            if not entry or idx >= len(entry):
                return None
            if not isinstance(entry[idx], str):
                raise ParseError()
            return entry[idx]
        if isinstance(entry, str):
            return entry if main else None
    return selector_instance


class Flatten(list):
    def __init__(self, obj):
        self._flat(obj)

    def _flat(self, obj, chain=[]):
        if not obj:
            return
        if isinstance(obj, dict):
            for k, v in obj.items():
                self._flat(v, chain + [k])
        # elif isinstance(obj, list) and isinstance(obj[0], list):
        # DEV: nested lists for one key-value -- to split lexems logically w/o name.
        else:
            self.append([chain, obj])


# NOTE all lexems have the same group -- like fza_Pronounce, which repeats
class SynGen:
    def __init__(self, lang):
        self.clr = Flatten(FileLoader.import_yaml('colorscheme'))
        self.dom = Flatten(FileLoader.import_yaml('lexems-' + lang))
        print(self.clr)

    def _select(self, fsel, dom):
        return [[grp, [fsel(x) for x in ws if fsel(x)]] for grp, ws in dom]

    def _adapt(self, lst):
        return [[''.join(grp), '|'.join(ws)] for grp, ws in lst]

    def _syntax(self, fmt, lst):
        return [fmt.format(grp, rgx) for grp, rgx in lst if grp and rgx]

    def _print(self, fmt, fsel):
        return self._syntax(fmt, self._adapt(self._select(fsel, self.dom)))


    def origin(self, fsel=_F_selector('origin', 0, True)):
        return self._print("syn match fza_{:s} '\\v\\c{:s}'\n", fsel)

    def phonetic(self):
        return self.origin(_F_selector('phonetic', 1))

    def colors(self):
        return self._print("hi def fza_{:s} ctermbg=None guibg=None ctermfg=112 \"{:s}\n",
                           lambda x: str(2))


# NOTE additional fields in word is not supposed to be included into syntax
# highlighting, but can be used for generating popups in some markups.
if __name__ == '__main__':
    syntax = SynGen('jap')
    for nm in ['origin', 'phonetic', 'colors']:
        FileLoader.export_cache(nm, getattr(syntax, nm)())
